# Generated by Django 4.1.7 on 2023-02-19 13:08

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import pay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Не менее одного товара')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары заказа',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Скидка')),
                ('percent', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Скидка в %')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена без налогов и скидок')),
                ('currency', models.CharField(choices=[('rub', 'Rub'), ('usd', 'Usd')], default='usd', max_length=3, verbose_name='Валюта')),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена без скидки')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Финальная цена')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pay.discount', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Налог')),
                ('percent', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Налог в %')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=pay.models.num_order, max_length=10, unique=True, verbose_name='Номер заказа')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена в рублях')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена в долларах')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(related_name='orders', through='pay.AmountItem', to='pay.item', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, related_name='items', to='pay.tax', verbose_name='Налог'),
        ),
        migrations.AddField(
            model_name='amountitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_item', to='pay.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='amountitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_item', to='pay.order', verbose_name='Заказ'),
        ),
        migrations.AddConstraint(
            model_name='amountitem',
            constraint=models.UniqueConstraint(fields=('item', 'order'), name='unique_item_order'),
        ),
    ]
